editorial_office/urls.py
from django.urls import path
from django.views.generic import TemplateView

from editorial_office.views import (
    index,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDeleteView,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    toggle_assign_to_newspaper,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list",
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create",
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path("newspapers/", NewspaperListView.as_view(), name="newspaper-list"),
    path("newspapers/<int:pk>/", NewspaperDetailView.as_view(), name="newspaper-detail"),
    path("newspapers/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path("newspapers/<int:pk>/update/", NewspaperUpdateView.as_view(), name="newspaper-update"),
    path("newspapers/<int:pk>/delete/", NewspaperDeleteView.as_view(), name="newspaper-delete"),
    path(
        "newspapers/<int:pk>/toggle-assign/",
        toggle_assign_to_newspaper,
        name="toggle-newspaper-assign",
    ),
    path("redactor/", RedactorListView.as_view(), name="redactor-list"),
    path(
        "redactor/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"
    ),
    path("redactor/", RedactorListView.as_view(), name="redactor-list"),
    path(
        "redactor/<int:pk>/", RedactorDetailView.as_view(), name="redactor-detail"
    ),
    path("redactor/create/", RedactorCreateView.as_view(), name="redactor-create"),
    path(
        "redactor/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactor/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
    path("", TemplateView.as_view(template_name="editorial_office/index.html"), name="index"),
]

app_name = "editorial_office"

newspaper_agency/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("editorial_office.urls", namespace="editorial_office")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

editorial_office/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    year_of_experience = models.PositiveIntegerField(default=1)

    class Meta:
        verbose_name = "publisher"
        verbose_name_plural = "publishers"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("editorial_office:redactor-detail", kwargs={"pk": self.pk})


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField(max_length=5000)
    published_date = models.DateField(auto_now_add=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE,)
    publishers = models.ManyToManyField(Redactor, related_name="newspapers", blank=True)

    def __str__(self):
        return f"{self.title} ({self.published_date})"

editorial_office/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from editorial_office.models import Newspaper, Redactor, Topic


class NewspaperForm(forms.ModelForm):
    publishers = forms.ModelMultipleChoiceField(
        queryset=Redactor.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "year_of_experience",
            "first_name",
            "last_name",
        )


class RedactorYearsOfExperienceUpdateForm(forms.ModelForm):
    class Meta:
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "year_of_experience",
            "first_name",
            "last_name",
        )


class NewspaperSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "search by title"
            }
        ),
    )


class RedactorSearchForm(forms.Form):
    publishers = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "search by username"
            }
        ),
    )


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "search by name"
            }
        ),
    )

editorial_office/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from editorial_office.forms import (
    RedactorYearsOfExperienceUpdateForm,
    RedactorCreationForm,
    RedactorSearchForm,
    NewspaperSearchForm,
    TopicSearchForm,
    NewspaperForm,
)
from editorial_office.models import Redactor, Newspaper, Topic


@login_required
def index(request):
    """View function for the home page of the site."""

    num_publishers = Redactor.objects.count()
    num_newspapers = Newspaper.objects.count()
    num_topics = Topic.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_publishers": num_publishers,
        "num_newspapers": num_newspapers,
        "num_topics": num_topics,
        "num_visits": num_visits + 1,
    }

    return render(request, "editorial_office/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    context_object_name = "topic_list"
    template_name = "editorial_office/topic_list.html"
    paginate_by = 5
    queryset = Topic.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = TopicSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        form = TopicSearchForm(self.request.GET)
        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("editorial_office:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("editorial_office:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("editorial_office:topic-list")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    paginate_by = 5
    queryset = Newspaper.objects.select_related("topic")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data(**kwargs)

        title = self.request.GET.get("title", "")

        context["search_form"] = NewspaperSearchForm(initial={"title": title})
        return context

    def get_queryset(self):
        title = self.request.GET.get("title")

        if title:
            return self.queryset.filter(title__icontains=title)

        return self.queryset


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("editorial_office:newspaper-list")
    queryset = Newspaper.objects.select_related("topic")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("editorial_office:newspaper-list")
    queryset = Newspaper.objects.select_related("topic")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("editorial_office:newspaper-list")


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    paginate_by = 5
    context_object_name = "redactors_list"
    queryset = Redactor.objects.prefetch_related("newspapers__topic")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = RedactorSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        username = self.request.GET.get("username")

        if username:
            return self.queryset.filter(username__icontains=username)

        return self.queryset


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor
    queryset = Redactor.objects.prefetch_related("newspapers")


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorYearsOfExperienceUpdateForm
    success_url = reverse_lazy("editorial_office:redactor-list")


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("")


@login_required
def toggle_assign_to_newspaper(request, pk):
    publisher = Redactor.objects.get(id=request.user.id)
    if (
            Newspaper.objects.get(id=pk) in publisher.newspapers.all()
    ):
        publisher.newspapers.remove(pk)
    else:
        publisher.newspapers.add(pk)
    return HttpResponseRedirect(reverse_lazy("editorial_office:newspaper-detail", args=[pk]))


class LogoutView(generic.TemplateView):
    pass

templates/editorial_office/newspaper_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete newspaper?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/editorial_office/newspaper_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load static %}
{% block content %}
    <style>
        body {
            width: 500px;
            margin: auto;
            background-image: url("../../static/dist/assets/img/bg-signup.jpg");
            background-size: auto;
            background-repeat: no-repeat;
            background-position: center;
            color: #2c3034;
            border-radius: 25px;
        }
    </style>
  <body>
    <h1>{{ object|yesno:"Update,Create" }} newspaper</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Submit" class="btn btn-dark">
    </form>
  </body>
{% endblock %}

templates/editorial_office/newspaper_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Newspaper Agency</title>
    <link rel="icon" type="image/x-icon" href="../../static/dist/assets/favicon.ico"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet"/>
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="../../static/dist/css/styles.css" rel="stylesheet"/>
  </head>
  <body id="page-top">
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container px-4 px-lg-5">
      <a class="navbar-brand" href="#page-top">Start</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
              aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item"><a class="nav-link" style="font-size: 21px" href="{% url 'editorial_office:index' %}">Home</a>
          </li>
          <li class="nav-item"><a class="nav-link" style="font-size: 21px"
                                  href="{% url 'editorial_office:redactor-list' %}">Publishers</a></li>
          <li class="nav-item"><a class="nav-link" style="font-size: 21px"
                                  href="{% url 'editorial_office:newspaper-list' %}">Newspapers</a>
          </li>
          <li class="nav-item"><a class="nav-link" style="font-size: 21px"
                                  href="{% url 'editorial_office:topic-list' %}">Topics</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Masthead-->
  <header class="masthead">
    <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
      <div class="d-flex justify-content-center">
        <div class="text-center">
          <h1 class="mx-auto my-0 text-uppercase">Newspapers</h1>
          <h2 class="text-white-50 mx-auto mt-2 mb-5">Welcome to our editorial office</h2>
        </div>
      </div>
    </div>
  </header>
  <!-- About-->
  <section class="about-section text-center" id="about">
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-lg-8">
          <h2 class="text-white mb-4"> Newspapers List</h2>
          <ul class="text-white-50">
            <form method="get" action="" class="form-inline">
              {{ search_form|crispy }}
              <input class="btn btn-outline-light" type="submit" value="Search"/>
            </form>
            <hr>
            {% if newspaper_list %}
              <ul>
                {% for newspaper in newspaper_list %}
                  <li style="font-size: 21px;">
                    <a href="{% url "editorial_office:newspaper-detail" pk=newspaper.id %} ">{{ newspaper.title }}</a>
                    ("{{ newspaper.topic.name }}")
                  </li>
                {% endfor %}
              </ul>
            {% else %}
              <p>There are no newspapers in agency</p>
            {% endif %}
            <hr>
            {% block pagination %}
              {% include "includes/pagination.html" %}
            {% endblock %}
          </ul>
        </div>
      </div>
      <hr>
      <a href="{% url 'editorial_office:newspaper-create' %}" class="btn btn-primary">
        Create
      </a>
      {#      <img class="img-fluid" src="../../static/dist/assets/img/ipad.png" alt="..."/>#}
    </div>
  </section>

  <!-- Footer-->
  <footer class="footer bg-black small text-center text-white-50">
    <div class="container px-4 px-lg-5">Newspaper agency 2024</div>
  </footer>
  <!-- Bootstrap core JS-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Core theme JS-->
  <script src="../../static/dist/js/scripts.js"></script>
  <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
  <!-- * *                               SB Forms JS                               * *-->
  <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
  <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
  <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
  </body>
  </html>
{% endblock %}

templates/editorial_office/publisher_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete publisher?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/editorial_office/redactor_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <h1>Delete publisher?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/editorial_office/redactor_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

  <html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Newspaper Agency</title>
    <link rel="icon" type="image/x-icon" href="../../static/dist/assets/favicon.ico"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet"/>
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="../../static/dist/css/styles.css" rel="stylesheet"/>
  </head>
  <body id="page-top">
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container px-4 px-lg-5">
      <a class="navbar-brand" href="#page-top">Start</a>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item"><a class="nav-link" style="font-size: 21px" href="{% url 'editorial_office:index' %}">Home</a>
          </li>
          <li class="nav-item"><a class="nav-link" style="font-size: 21px"
                                  href="{% url 'editorial_office:redactor-list' %}">Publishers</a></li>
          <li class="nav-item"><a class="nav-link" style="font-size: 21px"
                                  href="{% url 'editorial_office:newspaper-list' %}">Newspapers</a>
          </li>
          <li class="nav-item"><a class="nav-link" style="font-size: 21px"
                                  href="{% url 'editorial_office:topic-list' %}">Topics</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Masthead-->
  <header class="masthead">
    <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
      <div class="d-flex justify-content-center">
        <div class="text-center">
          <h2 class="mx-auto my-0 text-uppercase">Username: {{ redactor.username }}</h2>
          <h2 class="text-white-50 mx-auto mt-2 mb-5">
            <li><strong>First name:</strong> {{ redactor.first_name }}</li>
            <li><strong>Last name:</strong> {{ redactor.last_name }}</li>
            <li><strong>Experience:</strong> {{ redactor.year_of_experience }}</li>
            <li><strong>Is staff:</strong> {{ redactor.is_staff }}</li>
          </h2>
        </div>
      </div>
    </div>
  </header>
  <!-- About-->
  <section class="about-section text-center" id="about">
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-lg-8">
          <h2 class="text-white mb-4">Publisher newspapers: </h2>
          <ul class="text-white-50">
            <p class="text-black-50 mb-0">{% for newspaper in redactor.newspapers.all %}
              <hr>
              <li><strong style="font-size: 21px">Title: </strong><a style="font-size: 21px"
                                                                     href="{% url 'editorial_office:newspaper-detail' pk=newspaper.id %}">{{ newspaper.title }}
                ({{ newspaper.topic.name }}) </a>
              </li>
            {% empty %}
              <br>
              <p>No newspapers!</p>
            {% endfor %}
            <br>
            <br>
            <a class="btn btn-primary" href="{% url 'editorial_office:redactor-delete' pk=redactor.id %}">Delete</a>
            <a class="btn btn-danger" href="{% url 'editorial_office:redactor-update' pk=redactor.id %}">Update</a>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <!-- Footer-->
  <footer class="footer bg-black small text-center text-white-50">
    <div class="container px-4 px-lg-5">Newspaper agency 2024</div>
  </footer>
  <!-- Bootstrap core JS-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Core theme JS-->
  <script src="../../static/dist/js/scripts.js"></script>
  <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
  <!-- * *                               SB Forms JS                               * *-->
  <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
  <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
  <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
  </body>
  </html>
{% endblock %}

templates/editorial_office/topic_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load static %}

{% block content %}

  <html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Newspaper Agency</title>
    <link rel="icon" type="image/x-icon" href="../../static/dist/assets/favicon.ico"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet"/>
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="../../static/dist/css/styles.css" rel="stylesheet"/>
  </head>
  <body id="page-top">
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container px-4 px-lg-5">
      <a class="navbar-brand" href="#page-top">Start</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
              aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item"><a class="nav-link" style="font-size: 21px" href="{% url 'editorial_office:index' %}">Home</a>
          </li>
          <li class="nav-item"><a class="nav-link" style="font-size: 21px"
                                  href="{% url 'editorial_office:redactor-list' %}">Publishers</a></li>
          <li class="nav-item"><a class="nav-link" style="font-size: 21px"
                                  href="{% url 'editorial_office:newspaper-list' %}">Newspapers</a>
          </li>
          <li class="nav-item"><a class="nav-link" style="font-size: 21px"
                                  href="{% url 'editorial_office:topic-list' %}">Topics</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Masthead-->
  <header class="masthead">
    <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
      <div class="d-flex justify-content-center">
        <div class="text-center">
          <h1 class="mx-auto my-0 text-uppercase">Topics</h1>
          <h2 class="text-white-50 mx-auto mt-2 mb-5">Welcome to our editorial office</h2>
        </div>
      </div>
    </div>
  </header>
  <!-- About-->
  <section class="about-section text-center" id="about">
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-lg-8">
          <h2 class="text-white mb-4"> Topic List</h2>
          <ul class="text-white-50">
            <form method="get" action="" class="form-inline">
              {{ search_form|crispy }}
              <input class="btn btn-outline-light" type="submit" value="Search"/>
            </form>
            <hr>
            {% if topic_list %}
              <table class="table">
                <tr>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Update</th>
                  <th>Delete</th>
                </tr>

                {% for topic in topic_list %}
                  <tr>
                    <td style="color: white">
                      {{ topic.id }}
                    </td>
                    <td style="font-size: 21px; color: white">
                      {{ topic.name }}
                    </td>
                    <td>
                      <a style="font-size: 21px" href="{% url 'editorial_office:topic-update' pk=topic.id %}">
                        Update
                      </a>
                    </td>
                    <td>
                      <a style="font-size: 21px; color: red"
                         href="{% url 'editorial_office:topic-delete' pk=topic.id %}">
                        Delete
                      </a>
                    </td>
                  </tr>
                {% endfor %}
              </table>

            {% else %}
              <p>There are no topics in the newspaper.</p>
            {% endif %}
            {% block pagination %}
              {% include "includes/pagination.html" %}
            {% endblock %}
          </ul>
        </div>
      </div>
      <hr>
      <a href="{% url 'editorial_office:topic-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </div>
  </section>

  <!-- Footer-->
  <footer class="footer bg-black small text-center text-white-50">
    <div class="container px-4 px-lg-5">Newspaper agency 2024</div>
  </footer>
  <!-- Bootstrap core JS-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Core theme JS-->
  <script src="../../static/dist/js/scripts.js"></script>
  <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
  <!-- * *                               SB Forms JS                               * *-->
  <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
  <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
  <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
  </body>
  </html>
{% endblock %}